# Name of the workflow, which will appear in the "Actions" tab of your GitHub repo
name: Frontend Pull Request Check

# This section defines the trigger for the workflow.
on:
  # Run this workflow when a pull request is created or updated
  pull_request:
    # Only run for pull requests that target the 'main' branch
    branches:
      - main
    # Only consider files within the 'frontend' directory
    paths:
      - 'frontend/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # We have a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set the default working directory for all steps in this job
    defaults:
      run:
        working-directory: ./frontend

    # A sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Sets up the latest LTS version of Node.js (v22.x)
      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # <-- UPDATED from '20.x' to the latest LTS
          # This step caches npm dependencies to speed up subsequent workflow runs
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Step 3: Install dependencies using 'npm ci'
      # 'npm ci' is generally faster and more reliable for CI environments than 'npm install'
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run the linter to check code formatting and quality
      - name: Lint Code
        run: npm run lint

      # Step 5: Run the test suite
      # The '--if-present' flag ensures this step doesn't fail if you have no 'test' script yet
      - name: Run Tests
        run: npm test --if-present

      # Step 6: Create a production build to catch any build-time errors
      - name: Build Production App
        run: npm run build
